name: hrms
description: A new Flutter application.
version: 1.3.0+12

environment:
  sdk: '>=2.17.0 <4.0.0'

# dependencies:
#   flutter:
#     sdk: flutter
#   cupertino_icons: ^1.0.5

#   # Replaced unsupported calendar_strip with table_calendar
#   table_calendar: ^3.0.8

#   flutter_downloader: ^1.4.4
#   path_provider: ^2.0.2
#   permission_handler: ^6.1.1
#   geolocator: ^9.0.1
#   profile: ^0.0.1
#   connectivity_plus_web: ^1.2.5

#   camera: ^0.9.4+18
#   hive_flutter: ^1.1.0
#   image: ^3.1.3
#   lottie: ^1.2.2
#   geocoding: ^2.1.0

#   shared_preferences: ^2.0.6
#   provider: ^6.0.3
#   http: ^0.13.3
#   fluttertoast: ^8.0.7
#   material_design_icons_flutter: ^6.0.7096
#   rxdart: ^0.27.1

#   # Replaced flutter_circular_chart with percent_indicator
#   percent_indicator: ^4.2.3

#   charts_flutter: ^0.11.0  # Uses intl ^0.17.0
#   flutter_vector_icons: ^2.0.0
#   flutter_screenutil: ^5.0.0+2
#   flutter_svg: ^1.0.3
#   device_info: ^2.0.2
#   intl: ^0.17.0  # Compatible with charts_flutter
#   location: ^5.0.1
#   google_maps_flutter: ^2.0.6

#   # Replaced latlong (non-null-safe) with latlong2
#   latlong2: ^0.8.1

#   sqflite: ^2.0.0+3
#   image_picker: ^0.8.7+1
#   flutter_plugin_android_lifecycle: ^2.0.2
#   flutter_calendar_carousel: ^2.4.1
#   package_info: ^2.0.2
#   url_launcher: ^6.0.9
#   launch_review: ^3.0.1
#   flutter_speed_dial: ^6.0.0
#   community_material_icon: ^5.9.55
#   connectivity_plus: ^3.0.2

#   firebase_core: ^2.13.0
#   firebase_messaging: ^14.6.1
#   firebase_analytics: ^10.4.1
#   firebase_crashlytics: ^3.3.1

#   cached_network_image: ^3.1.0+1
#   youtube_player_flutter: ^8.1.1
#   # flutter_local_notifications: ^9.7.0
#   flutter_local_notifications: ^17.1.2
#   autocomplete_textfield: ^2.0.1
#   flutter_map_tappable_polyline: ^3.0.0
#   flutter_inappwebview: ^5.7.1+2
#   font_awesome_flutter: ^10.1.0
#   file_picker: ^4.3.2
#   dio: ^4.0.4
#   downloads_path_provider_28: ^0.1.0
#   open_file: ^3.0.1
#   timer_builder: ^2.0.0
#   loading_btn: ^1.0.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # table_calendar: ^3.0.9
  flutter_downloader: ^1.11.4           # last stable supporting <4.0.0
  # path_provider: ^2.0.14
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  profile: ^0.0.1
  # connectivity_plus_web: ^1.2.5

  camera: ^0.11.2
  hive_flutter: ^1.1.0
  image: ^4.5.4
  lottie: ^3.3.1
  geocoding: ^4.0.0

  shared_preferences: ^2.0.18
  provider: ^6.0.5
  http: ^1.4.0
  fluttertoast: ^8.2.4
  material_design_icons_flutter: ^7.0.7296
  rxdart: ^0.28.0

  percent_indicator: ^4.2.3
  # charts_flutter: ^0.12.0
  flutter_vector_icons: ^2.0.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.2.0
  # intl: ^0.17.0
  location: ^8.0.1
  google_maps_flutter: ^2.3.0

  # latlong2: ^0.9.1
  sqflite: ^2.2.8+4
  image_picker: ^1.1.2
  flutter_plugin_android_lifecycle: ^2.0.16
  # flutter_calendar_carousel: ^2.4.2
  # package_info: ^2.0.2
  url_launcher: ^6.1.7
  # launch_review: ^3.0.1
  flutter_speed_dial: ^7.0.0
  community_material_icon: ^5.9.55
  # connectivity_plus: ^3.0.6

  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0

  cached_network_image: ^3.2.3
  # youtube_player_flutter: ^8.1.2
  # flutter_local_notifications: ^13.0.0   # ✅ Compatible with <4.0.0
  autocomplete_textfield: ^2.0.1
  flutter_map_tappable_polyline: ^6.0.0
  # flutter_inappwebview: ^5.7.2
  font_awesome_flutter: ^10.4.0
  # file_picker: ^5.3.2
  dio: ^5.3.2
  # downloads_path_provider_28: ^0.1.1
  open_file: ^3.3.2
  timer_builder: ^2.0.0
 
  loading_btn: ^1.0.3
  table_calendar: ^3.0.8
  intl: ^0.19.0
  # charts_flutter: ^0.12.0
  flutter_calendar_carousel: ^2.4.4
  file_picker: ^10.2.1
  flutter_local_notifications: ^19.4.0
  connectivity_plus: ^6.0.3
  device_info_plus: ^11.3.0
  # connectivity_plus_web: ^2.0.0
  flutter_inappwebview: ^6.0.0-beta.26
  youtube_player_flutter: ^9.1.1
  # launch_review: ^3.0.1
  in_app_review: ^2.0.8
  package_info_plus: ^8.3.0
  timezone: ^0.10.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
    - assets/gif/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Bold.ttf
        - asset: assets/fonts/NunitoSans-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
